robots:
  jvrc1:
    frames:
      - name: LeftHandGraspFrame
        parent: l_wrist
        X_p_f:
          translation: [0.0, -0.0085, -0.110]
      - name: RightHandOpenFrame
        parent: r_wrist
        X_p_f:
          translation: [0.0, 0.0085, -0.1225]
  sample_field:
    module: MCC/SampleField

transitions:
  - [MCC::Initial_, OK, MCC::ConfigMotion1_, Auto]
  - [MCC::ConfigMotion1_, OK, MCC::ConfigMotion2_, Auto]

states:
  MCC::Initial_:
    base: MCC::Initial
    configs:
      autoStartTime: 2.0
      gripperCommands:
        - name: l_gripper
          opening: 1.0
        - name: r_gripper
          opening: 1.0

  MCC::ConfigMotion1_:
    base: MCC::ConfigMotion
    configs:
      baseTime: Relative
      stepCommandList:
        - limb: LeftFoot
          type: Add
          startTime: 2.0
          endTime: 3.0
          pose:
            translation: [0.2, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 3.5
          endTime: 4.5
          pose:
            translation: [0.4, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftFoot
          type: Add
          startTime: 5.0
          endTime: 6.0
          pose:
            translation: [0.6, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 6.5
          endTime: 7.5
          pose:
            translation: [0.6, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftHand
          pose:
            translation: [0.9, 0.5, 0.8]
            rotation: [0.2617993877991494, 0, 0]
          swingCommand:
            type: Add
            startTime: 7.0
            endTime: 9.0
            config:
              approachOffset: [0, 0, 0.10]
          contactCommandList:
            - time: 9.0
              constraint:
                type: Empty
            - time: 10.0
              constraint:
                type: Grasp
                fricCoeff: 1.0
          gripperCommandList:
            - time: 9.0
              name: l_gripper
              config:
                opening: 0.0
        - limb: RightFoot
          type: Add
          startTime: 10.5
          endTime: 11.5
          pose:
            translation: [0.9, -0.15, 0.05]
            rotation: [-0.3490658503988659, 0, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftFoot
          type: Add
          startTime: 12.0
          endTime: 13.5
          pose:
            translation: [1.2, 0.1, 0.0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 14.0
          endTime: 15.0
          pose:
            translation: [1.2, -0.1, 0.0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftHand
          swingCommand:
            type: Remove
            startTime: 16.5
            endTime: 18.5
            config:
              withdrawOffset: [0, 0, 0.10]
          contactCommandList:
            - time: 15.5
              constraint:
                type: Empty
            - time: 16.5
              constraint: {}
          gripperCommandList:
            - time: 15.5
              name: l_gripper
              config:
                opening: 1.0
        - limb: LeftFoot
          type: Add
          startTime: 18.0
          endTime: 19.0
          pose:
            translation: [1.4, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 19.5
          endTime: 20.5
          pose:
            translation: [1.6, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftFoot
          type: Add
          startTime: 21.0
          endTime: 22.0
          pose:
            translation: [1.8, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 22.5
          endTime: 23.5
          pose:
            translation: [1.8, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightHand
          type: Add
          pose:
            translation: [1.8, -0.7, 1.0]
            rotation: [-1.5707963267948966, 0, 0]
          startTime: 24.0
          endTime: 26.0
          constraint:
            type: Surface
            fricCoeff: 0.5
          swingConfig:
            approachOffset: [0, 0, 0.10]
        - limb: RightHand
          type: Remove
          startTime: 29.0
          endTime: 31.0
          swingConfig:
            withdrawOffset: [0, 0, 0.10]
      nominalCentroidalPoseList:
        - time: 26.5
          pose:
            translation: [0.0, -0.25, 0.80]
        - time: 28.5
          pose:
            translation: [0.0, 0.0, 0.80]
      collisionConfigList:
        - time: 5.0
          type: Add
          r1: jvrc1
          r2: sample_field
          collisions:
            - body1: L_WRIST_Y_S
              body2: HandleLeftHand1
              iDist: 0.15
              sDist: 0.10
        - time: 8.5
          type: Remove
          r1: jvrc1
          r2: sample_field
        - time: 17.0
          type: Add
          r1: jvrc1
          r2: sample_field
          collisions:
            - body1: L_WRIST_Y_S
              body2: HandleLeftHand1
              iDist: 0.15
              sDist: 0.10
        - time: 20.5
          type: Remove
          r1: jvrc1
          r2: sample_field

  MCC::ConfigMotion2_:
    base: MCC::ConfigMotion
    configs:
      baseTime: Relative
      stepCommandList:
        - limb: LeftFoot
          type: Add
          startTime: 6.0
          endTime: 6.3
          pose:
            translation: [1.8, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 6.0
          endTime: 6.3
          pose:
            translation: [1.8, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftFoot
          type: Add
          startTime: 6.6
          endTime: 6.9
          pose:
            translation: [1.8, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 6.6
          endTime: 6.9
          pose:
            translation: [1.8, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: LeftFoot
          type: Add
          startTime: 7.2
          endTime: 7.5
          pose:
            translation: [1.8, 0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
        - limb: RightFoot
          type: Add
          startTime: 7.2
          endTime: 7.5
          pose:
            translation: [1.8, -0.1, 0]
          constraint:
            type: Surface
            fricCoeff: 0.5
      taskConfigList:
        - time: 4.0
          name: MomentumTask
          stiffness: 100.0
          weight: 1000.0
          dimWeight: [1, 1, 1, 0, 0, 0]
        - time: 8.0
          name: MomentumTask
          stiffness: 1.0
          weight: 0.0
          dimWeight: [1, 1, 1, 1, 1, 1]

LimbTaskList:
  - type: firstOrderImpedance
    limb: LeftFoot
    frame: LeftFootCenter
    cutoffPeriod: 0.01
    weight: 1000.0
  - type: firstOrderImpedance
    limb: RightFoot
    frame: RightFootCenter
    cutoffPeriod: 0.01
    weight: 1000.0
  - type: firstOrderImpedance
    limb: LeftHand
    frame: LeftHandGraspFrame
    cutoffPeriod: 0.01
    weight: 1000.0
  - type: firstOrderImpedance
    limb: RightHand
    frame: RightHandOpenFrame
    cutoffPeriod: 0.01
    weight: 1000.0

LimbManagerSet:
  LimbManager:
    Hand:
      impedanceGains:
        MultiContact:
          damper:
            linear: [5e4, 5e4, 5e4]
            angular: [100, 100, 100]
          spring:
            linear: [0, 0, 0]
            angular: [0, 0, 2000]
          wrench:
            linear: [1, 1, 1]
            angular: [1, 1, 0]

OverwriteConfigList:
  NoSensors:
    LimbManagerSet:
      LimbManager:
        Hand:
          impedanceGains:
            SingleContact:
              wrench:
                linear: [0, 0, 0]
                angular: [0, 0, 0]
            MultiContact:
              wrench:
                linear: [0, 0, 0]
                angular: [0, 0, 0]
            Swing:
              wrench:
                linear: [0, 0, 0]
                angular: [0, 0, 0]

  jvrc1:
    PostureTask:
      target:
        # https://github.com/jrl-umi3218/mc_rtc/blob/d297558acdbfe9514d27ebd5996e2f89728878b6/src/mc_robots/jvrc1.cpp#L82-L85
        # TODO: This configuration will no longer be necessary when https://github.com/jrl-umi3218/mc_rtc/issues/353 is resolved
        R_SHOULDER_P: [-0.052]
        R_SHOULDER_R: [-0.17]
        R_SHOULDER_Y: [0.0]
        R_ELBOW_P: [-0.52]
        R_ELBOW_Y: [0.0]
        R_WRIST_R: [0.0]
        R_WRIST_Y: [0.0]
        L_SHOULDER_P: [-0.052]
        L_SHOULDER_R: [0.17]
        L_SHOULDER_Y: [0.0]
        L_ELBOW_P: [-0.52]
        L_ELBOW_Y: [0.0]
        L_WRIST_R: [0.0]
        L_WRIST_Y: [0.0]

    CentroidalManager:
      nominalCentroidalPose:
        translation: [0.0, 0.0, 0.80]

    Contacts:
      Surface:
        - name: LeftFoot
          vertices: [[-0.1, -0.04, 0.0], [-0.1, 0.04, 0.0], [0.1, 0.04, 0.0], [0.1, -0.04, 0.0]]
        - name: RightFoot
          vertices: [[-0.1, -0.04, 0.0], [-0.1, 0.04, 0.0], [0.1, 0.04, 0.0], [0.1, -0.04, 0.0]]
        - name: LeftHand
          vertices: [[0.025, 0.05, 0.0], [-0.025, 0.05, 0.0], [0.0, -0.05, 0.0]]
        - name: RightHand
          vertices: [[0.025, -0.05, 0.0], [-0.025, -0.05, 0.0], [0.0, 0.05, 0.0]]

      Grasp:
        - name: LeftHand
          vertices:
            - translation: [0.025, 0.015, 0]
              rotation: [1.5707963267948966, 0, 0]
            - translation: [-0.025, 0.015, 0]
              rotation: [1.5707963267948966, 0, 0]
            - translation: [0.025, -0.015, 0]
              rotation: [-1.5707963267948966, 0, 0]
            - translation: [-0.025, -0.015, 0]
              rotation: [-1.5707963267948966, 0, 0]
        - name: RightHand
          vertices:
            - translation: [0.025, 0.015, 0]
              rotation: [1.5707963267948966, 0, 0]
            - translation: [-0.025, 0.015, 0]
              rotation: [1.5707963267948966, 0, 0]
            - translation: [0.025, -0.015, 0]
              rotation: [-1.5707963267948966, 0, 0]
            - translation: [-0.025, -0.015, 0]
              rotation: [-1.5707963267948966, 0, 0]
